image:
  repository:  #set your image repository
  pullPolicy: IfNotPresent

daemonsets:
  kubernetes-cleanup:
    enabled: true
    label: kubernetes-cleanup
    name: kubernetes-cleanup
    version: latest
    deployment:
      resources:
        requests:
          cpu: 200m
          memory: 100Mi
        limits:
          cpu: 250m
          memory: 150Mi